version: '3.8'

services:
app:
build: .
ports:
- "8080:8080"
depends_on:
- redis
- mongodb
environment:
REDIS_HOST: redis
MONGO_URI: mongodb://mongodb:27017/mydb

redis:
image: redis:latest

mongodb:
image: mongo:latest