# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-inbev-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: app
          image: ${{ secrets.DOCKER_HUB_USER }}/ab-inbev:latest
          ports:
            - containerPort: 8080
