# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ab-inbev-go-service
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 8080
      targetPort: 8080
      protocol: TCP
