name: ab-inbev-ci-cd-go-workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/ab-inbev:latest
  deploy:
    runs-on: ubuntu-22.04
    needs: [build-and-push]
    steps:
      - uses: actions/checkout@v3

      - name: Set Kubernetes context
        uses: Azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy to Kind cluster
        uses: Azure/k8s-deploy@v4
        with:
          images: ${{ secrets.DOCKER_HUB_USER }}/ab-inbev:latest
          manifests: |
            k8s/deployment.yaml
